
export default class CommonSaying {

    private phrases :string[] = [
        "A buon cavalier non manca lancia",
        "A buon cavallo non manca sella",
        "A buon intenditor poche parole",
        "A caval donato non si guarda in bocca",
        "A chi batte forte, si apron le porte",
        "A chi non vuol far fatiche, il terreno produce ortiche",
        "A chi troppo e a chi niente",
        "A chi ti porge un dito non prendere la mano",
        "A goccia a goccia si scava la pietra",
        "A gran salita, gran discesa",
        "A lavar la testa all'asino si perde il ranno e il sapone",
        "Altezza mezza bellezza",
        "A mali estremi estremi rimedi",
        "A muro basso ognuno ci si appoggia",
        "A pagare e a morire c'è sempre tempo",
        "A pensar male, s'indovina sempre",
        "A rubar poco si va in galera, a rubar tanto si fa carriera",
        "A tutto c'è rimedio fuorché alla morte",
        "Abbattuto l'albero scompare l'ombra",
        "Acquista buona fama e mettiti a dormire",
        "Ad ogni primavera segue un autunno",
        "Acqua cheta rompe i ponti",
        "Ad ognuno la sua croce",
        "Ai pazzi si dà sempre ragione",
        "Aiutati che Dio t'aiuta",
        "Al bisogno si conosce l'amico",
        "Al buio la villana è bella quanto la dama",
        "Al cuore non si comanda",
        "Al primo colpo non cade l'albero",
        "Amor che nasce di malattia, quando si guarisce passa via",
        "Anche fra le spine nascono le rose",
        "Anche i fanciulli diventano uomini",
        "Anche il sole ha le sue macchie",
        "Anno nuovo vita nuova",
        "Assai domanda chi si lamenta",
        "Bacco, tabacco e Venere riducon l'uomo in cenere",
        "Battere il ferro finché è caldo",
        "Bella vigna poca uva",
        "Bene per male è carità, male per bene è crudeltà",
        "Bisogna mangiare per vivere e non vivere per mangiare",
        "Botte buona fa buon vino",
        "Buon sangue non mente",
        "Cambiano i suonatori ma la musica è sempre quella",
        "Campa cavallo che l'erba cresce",
        "Can che abbaia non morde",
        "Chi ben comincia è a metà dell'opera",
        "Chi cade in povertà, perde ogni amico",
        "48)Chi cento ne fa una ne aspetta",
        "Chi cerca, trova",
        "Chi di spada ferisce di spada perisce",
        "Chi di speranza vive disperato muore",
        "Chi dice donna dice danno",
        "Chi disprezza compra",
        "Chi domanda non erra",
        "Chi dorme non piglia pesci",
        "Chi è causa del suo mal pianga se stesso",
        "Chi è in difetto è in sospetto",
        "Chi è svelto a mangiare è svelto a lavorare",
        "Chi fa da sé fa per tre",
        "Chi fa l'altrui mestiere, fa la zuppa nel paniere",
        "Chi ha avuto ha avuto e chi ha dato ha dato",
        "Chi ha denti non ha pane e chi ha pane non ha denti",
        "Chi ha tempo non aspetti tempo",
        "Chi la dura la vince",
        "Chi la fa l'aspetti",
        "Chi lascia la via vecchia per la nuova sa quel che lascia ma non sa quel che trova",
        "Chi mena per primo mena due volte",
        "Chi muore giace e chi vive si dà pace",
        "Chi nasce afflitto muore sconsolato",
        "Chi nasce è bello, chi si sposa è buono e chi muore è santo",
        "Chi nasce tondo non può morir quadrato",
        "Chi non beve in compagnia o è un ladro o è una spia",
        "Chi non ha testa abbia gambe",
        "Chi non lavora non mangia",
        "Chi non muore si rivede",
        "Chi non risica, non rosica",
        "Chi non sa leggere la sua scrittura è asino di natura",
        "Chi perde ha sempre torto",
        "Chi più ha più vuole",
        "Chi più ne ha più ne metta",
        "Chi più spende meno spende",
        "Chi prima arriva meglio alloggia",
        "Chi s'accapiglia si piglia",
        "Chi sa fa e chi non sa insegna",
        "Chi semina raccoglie",
        "Chi semina vento raccoglie tempesta",
        "Chi si contenta gode",
        "Chi si fa i fatti suoi campa cent'anni",
        "Chi si loda si sbrodaR",
        "Chi si somiglia si piglia",
        "Chi si vanta da solo non vale un fagiolo",
        "Chi si umilia sarà esaltato, chi si esalta sarà umiliato",
        "Chi sta tra due selle si trova col culo in terra",
        "Chi tace acconsente",
        "Chi tardi arriva male alloggia",
        "Chi troppo vuole nulla stringe",
        "Chi trova un amico trova un tesoro",
        "Chi va con lo zoppo, impara a zoppicare",
        "Chi va piano va sano e va lontano. Chi va forte va alla morte",
        "Chi vince ha sempre ragione",
        "Chi vivrà vedrà",
        "Col fuoco non si scherza",
        "Con le buone maniere si ottiene tutto",
        "Da cosa nasce cosa",
        "Dagli amici mi guardi Iddio che dai nemici mi guardo io",
        "Dimmi con chi vai, e ti dirò chi sei",
        "Dio li fa e poi li accoppia",
        "Dio vede e provvede",
        "Dire pane al pane e vino al vino",
        "Donna al volante, pericolo costante",
        "Donna barbuta sempre piaciuta",
        "Donna nana tutta tana",
        "Dove entra la fortuna, esce l'umiltà",
        "È inutile piangere sul latte versato",
        "È la donna che fa l'uomo",
        "Fare buon viso a cattivo gioco",
        "Fare di necessità virtù",
        "Fatta la legge trovato l'inganno",
        "Finché c'è vita c'è speranza",
        "Fidarsi è bene, non fidarsi è meglio",
        "Fortunato al gioco, sfortunato in amore",
        "Gallina vecchia fa buon brodo",
        "Gioco di mano gioco di villano",
        "Gli errori si pagano",
        "Gli estremi si toccano",
        "Guardare e non toccare è una cosa da imparare",
        "Guardati da cane rabbioso e da uomo sospettoso",
        "I figli sono pezzi di cuore",
        "I peccati di gioventù si piangono in vecchiaia",
        "I soldi non fanno la felicità",
        "Il bue dice cornuto all'asino",
        "Il cane è il miglior amico dell'uomo",
        "Il diavolo fa le pentole ma non i coperchi",
        "Il dubbio è padre del sapere",
        "Il figlio al padre s'assomiglia, alla madre la figlia",
        "Il gatto ama i pesci, ma non vuole bagnarsi le zampe",
        "Il gatto che si è bruciato, ha paura anche dell'acqua fredda",
        "Il gioco è bello quando dura poco",
        "Il lavoro nobilita l'uomo",
        "Il letto si chiama rosa, se non si dorme si riposa",
        "Il lupo perde il pelo ma non il vizio",
        "Il pesce puzza dalla testa",
        "Il primo amore non si scorda mai",
        "Il riso abbonda sulla bocca degli stolti",
        "Il silenzio è d'oro e la parola d'argento",
        "Il tempo è denar",
        "Impara l'arte e mettila da parte",
        "L'abito non fa il monaco",
        "L'amore è cieco",
        "L'amore fa passare il tempo e il tempo fa passare l'amore",
        "L'amore non è bello se non è litigarello.",
        "L'apparenza inganna",
        "L'appetito vien mangiando",
        "L'eccezione conferma la regola",
        "L'erba del vicino è sempre più verde",
        "L'erba voglio non cresce nemmeno nel giardino del re",
        "L'occasione fa l'uomo ladro",
        "L'occhio del padrone ingrassa il cavallo",
        "L'ospite è come il pesce: dopo tre giorni puzza",
        "L'ozio è il padre di tutti i vizi",
        "L'unione fa la forza",
        "La bestemmia gira gira torna addosso a chi la tira",
        "La corda troppo tesa si spezza",
        "La difficoltà sta nell'iniziare",
        "La fortuna aiuta gli audaci",
        "La gatta frettolosa fece i gattini ciechi",
        "La lingua batte dove il dente duole",
        "La madre degli imbecilli è sempre incinta",
        "La miglior difesa è l'attacco",
        "La notte porta consiglio",
        "La pazienza è la virtù dei forti",
        "La ruota della fortuna gira",
        "La speranza è l'ultima a morire",
        "La speranza è la ricchezza dei poveri",
        "La verità viene sempre a galla",
        "Le bugie hanno le gambe corte",
        "Le disgrazie non vengono mai sole",
        "Le donne ne sanno una più del diavolo",
        "Le vie del Signore sono infinite",
        "Mal comune mezzo gaudio",
        "Male non fare, paura non avere",
        "Meglio un uovo oggi che una gallina domani",
        "Meglio poco che niente",
        "Meglio soli che male accompagnati",
        "Meglio tardi che mai",
        "Meglio un asino vivo che un dottore morto",
        "Moglie e buoi dei paesi tuoi",
        "Molto fumo e poco arrosto",
        "Morto un papa se ne fa un altro",
        "Ne uccide più la lingua che la spada",
        "Nel regno dei ciechi anche un orbo è re",
        "Nella botte piccola c'è il buon vino",
        "Non si muove foglia che Dio non voglia",
        "Non c'è due senza tre",
        "Non c'è miglior cieco di quello che non vuole vedere",
        "Non c'è peggior sordo di chi non vuol sentire",
        "Non c'è regola senza eccezioni",
        "Non c'è rosa senza spine",
        "Non destare il can che dorme",
        "Non dire quattro se non l'hai nel sacco",
        "Non è tutto oro quel che luccica",
        "Non fare agli altri quello che non vorresti fosse fatto a te",
        "Non fare il male ch'è peccato, non fare il bene ch'è sprecato",
        "Non fare il passo più lungo della gamba",
        "Non si fa niente per niente",
        "Non si finisce mai di imparare",
        "Non si può avere la botte piena e la moglie ubriaca",
        "Non tutte le ciambelle riescono col buco.",
        "Non tutto il male vien per nuocere",
        "Occhio non vede, cuore non duole",
        "Occhio per occhio, dente per dente",
        "Oggi a me domani a te",
        "Ogni giorno non è festa",
        "Ogni lasciata è persa",
        "Ogni medaglia ha il suo rovescio",
        "Ognuno faccia il suo mestiere",
        "Ognuno ha la sua croce",
        "Ognuno tira l'acqua al suo mulino",
        "Paese che vai usanza che trovi",
        "Patti chiari amicizia lunga",
        "Piove sempre sul bagnato",
        "Quando c'è la salute c'è tutto",
        "Quando il gatto non c'è i topi ballano",
        "Quando la pera è matura casca da sé",
        "Quando si mangia non si parla",
        "Quando la volpe non arriva all'uva dice che è acerba",
        "Ride ben chi ride ultimo",
        "Roma non fu fatta in un giorno",
        "Pietra che rotola non fa muschio",
        "Sbagliando s'impara",
        "Sbagliando s'impara",
        "Scherza coi fanti e lascia stare i Santi",
        "Se son rose fioriranno",
        "Se vuoi che t'ami, fa' che ti brami",
        "Senza denari non si canta messa",
        "Si dice il peccato, ma non il peccatore",
        "Si stava meglio quando si stava peggio",
        "Sposa bagnata sposa fortunata",
        "Stretta la foglia, larga la via dite la vostra che ho detto la mia",
        "Tale padre, tale figlio",
        "Tanti pochi fanno un assai",
        "Tanto va la gatta al lardo che ci lascia lo zampino",
        "Tentar non nuoce",
        "Tira più un pelo di fica che un carro di buoi",
        "Tolta la causa, cessato l'effetto",
        "Tra i due litiganti il terzo gode",
        "Tra il dire e il fare c'è di mezzo il mare",
        "Tra moglie e marito non mettere il dito",
        "Troppi cuochi guastano la cucina",
        "Tutte le strade portano a Roma",
        "Tutti i nodi vengono al pettine",
        "Tutto ciò che dura a lungo annoia",
        "Tutto è bene quel che finisce bene",
        "Tutto il mondo è paese",
        "Un padre campa cento figli e cento figli non campano un padre",
        "Una bugia ha bisogno di sette bugie",
        "Una ciliegia tira l'altra",
        "Una mano lava l'altra e tutte e due lavano il viso",
        "Una mela al giorno leva il medico di torno",
        "Una rondine non fa primavera",
        "Uomo avvisato mezzo salvato",
        "Vi sono dei matti savi, e dei savi matti",
        "Vivi e lascia vivere",
    ]

    public getPhrase(): string {

        const phrasesNumberIndex: number = this.phrases.length - 1;

        return this.phrases[Math.floor(Math.random() * phrasesNumberIndex)];

    }

}